### ISSUE TITLE
x.py Fails to run successfully

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-sdk#3]
See error below (this is after a clean get)

bash-3.2$ ./x.py 
 > build: hedera-sdk-c/libs/x86_64-apple-darwin/libhedera.a
 - cargo build --features bridge:c --target x86_64-apple-darwin
    Updating git repository `https://github.com/mehcode/simple_asn1.git`
error: failed to resolve patches for `https://github.com/rust-lang/crates.io-index`

Caused by:
  failed to load source for a dependency on `simple_asn1`

Caused by:
  Unable to update https://github.com/mehcode/simple_asn1.git?rev=39793f754bffe73d8294718a9de7b8f1c9ddb2c9#39793f75

Caused by:
  revspec '39793f754bffe73d8294718a9de7b8f1c9ddb2c9' not found; class=Reference (4); code=NotFound (-3)
Traceback (most recent call last):
  File "./x.py", line 147, in <module>
    run(commit='--commit' in argv, release='--release' in argv)
  File "./x.py", line 99, in run
    build(target, commit=commit, release=release)
  File "./x.py", line 52, in build
    sh('cargo', 'build', profile, '--features', 'bridge:c', '--target', target, cwd='hedera-sdk-rust')
  File "./x.py", line 18, in sh
    return check_output(command, **options)
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 389, in check_output
    **kwargs).stdout
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 481, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['cargo', 'build', '--features', 'bridge:c', '--target', 'x86_64-apple-darwin']' returned non-zero exit status 101.

**Comment by mehcode** [comment]
Definitely pull and try again. This was resolved last Thursday or Friday when simple-asn1 pushed a new release with my bugfix.

**Comment by gregscullard** [comment]
That worked.
